version: '3'

services:
  data-proxy:
    image: node:18-bullseye-slim
    working_dir: /app
    ports:
      - "3000:3000"
    entrypoint: /app/entrypoint.sh
    command: yarn pdp
    volumes:
      - ./:/app:cached
      - node_modules:/app/node_modules

volumes:
  node_modules: